using System.Collections;

namespace FortniteChecker.Models
{
    static class GlobalVariables
    {
        public static string UserAgent = "Fortnite/++Fortnite+Release-4.5-CL-4166199 Windows/6.2.9200.1.768.64bit";

        public static string LoginUrl =
            "https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token";

        public static string AuthorizationValue =
            "basic ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ=";

        public static Hashtable Pickaxes = new Hashtable
        {
            { "boltonpickaxe", "Close Shave" },
            { "defaultpickaxe", "Default Pickaxe" },
            { "halloweenscythe", "Reaper" },
            { "happypickaxe", "Lucky" },
            { "pickaxe_deathvalley", "Death Valley" },
            { "pickaxe_flamingo", "Pink Flamingo" },
            { "pickaxe_id_011_medieval", "Axecalibur" },
            { "pickaxe_id_012_district", "Pulse Axe" },
            { "pickaxe_id_013_teslacoil", "AC/DC" },
            { "pickaxe_id_014_wintercamo", "Ice Breaker" },
            { "pickaxe_id_015_holidaycandycane", "Candy Axe" },
            { "pickaxe_id_016_disco", "Disco Brawl" },
            { "pickaxe_id_017_shark", "Chomp Jr." },
            { "pickaxe_id_018_anchor", "Bottom Feeder" },
            { "pickaxe_id_019_heart", "Tat Axe" },
            { "pickaxe_id_020_keg", "Party Animal" },
            { "pickaxe_id_021_megalodon", "Tooth Pick" },
            { "pickaxe_id_022_holidaygiftwrap", "You Shouldn't Have!" },
            { "pickaxe_id_023_skiboot", "Ski Boot" },
            { "pickaxe_id_024_plunger", "Plunja" },
            { "pickaxe_id_025_dragon", "Dragon Axe" },
            { "pickaxe_id_026_brite", "Rainbow Smash" },
            { "pickaxe_id_027_scavenger", "Sawtooth" },
            { "pickaxe_id_028_space", "EVA" },
            { "pickaxe_id_029_assassin", "Trusty No. 2" },
            { "pickaxe_id_030_artdeco", "Empire Axe" },
            { "pickaxe_id_031_squeak", "Pick Squeak" },
            { "pickaxe_id_032_tactical", "Tactical Spade" },
            { "pickaxe_lockjaw", "Raider's Revenge" },
            { "sicklebatpickaxe", "Batsickle" },
            { "skiicepickaxe", "Cliffhanger" },
            { "spikypickaxe", "Spiky" },
            { "pickaxe_id_033_potofgold", "Pot O' Gold" },
            { "pickaxe_id_034_rockerpunk", "Anarchy Axe" },
            { "pickaxe_id_035_prismatic", "Spectral Axe" },
            { "pickaxe_id_036_cuchulainn", "Silver Fang" },
            { "pickaxe_id_037_stealth", "Spectre" },
            { "pickaxe_id_038_carrot", "Carrot Stick" },
            { "pickaxe_id_039_tacticalblack", "Instigator" },
            { "pickaxe_id_040_pizza", "Axeroni" },
            { "pickaxe_id_041_pajamaparty", "Bitemark" },
            { "pickaxe_id_042_circuitbreaker", "Cutting Edge" },
            { "pickaxe_random", "Random Pickaxe" },
            { "pickaxe_id_043_orbitingplanets", "Global Axe" },
            { "pickaxe_id_044_tacticalurbanhammer", "Tenderizer" },
            { "pickaxe_id_045_valor", "Gale Force" },
            { "pickaxe_id_046_candy", "Lollipopper" },
            { "pickaxe_id_047_carbideblue", "Positron" },
            { "pickaxe_id_048_carbideblack", "Onslaught" },
            { "pickaxe_id_049_metal", "Persuader" },
            { "pickaxe_id_050_graffiti", "Renegade Roller" },
            { "pickaxe_id_051_neonglow", "Glow Stick" },
            { "pickaxe_id_052_hazmat", "Autocleave" },
            { "pickaxe_id_053_deco", "Airfoil" },
            { "pickaxe_id_054_filmcamera", "Director's Cut" },
            { "pickaxe_id_055_stop", "Stop Axe" },
            { "pickaxe_id_056_venus", "Tendril" },
            { "pickaxe_id_057_jailbird", "Nite Owl" },
            { "pickaxe_id_058_basketball", "Slam Dunk" },
            { "pickaxe_id_059_darkeagle", "Oracle Axe" },
            { "pickaxe_id_060_darkninja", "Fated Frame" },
            { "pickaxe_id_061_wwiipilot", "Propeller Axe" },
            { "pickaxe_id_062_soccer", "Elite Cleat" },
            { "pickaxe_id_063_vuvuzela", "Vuvuzela" },
            { "pickaxe_id_064_gumshoe", "Magnifying Axe" },
            { "pickaxe_id_065_speedyred", "Razor Edge" },
            { "pickaxe_id_066_flintlockred", "Crimson Axe" },
            { "pickaxe_id_067_taxi", "Victory Lap" },
            { "pickaxe_id_068_drift", "Rift Edge" },
            { "pickaxe_id_069_darkviking", "Permafrost" },
            { "pickaxe_id_070_viking", "Forebearer" },
            { "pickaxe_id_071_streetracer", "Lug Axe" },
            { "pickaxe_id_072_luchador", "Piledriver" },
            { "pickaxe_id_073_balloon", "Balloon Axe" },
            { "pickaxe_id_074_sharpdresser", "Studded Axe" },
            { "pickaxe_id_075_huya", "Pointer" },
            { "pickaxe_id_076_douyu", "Power Grip" },
            { "pickaxe_id_078_lifeguard", "Rescue Paddle" },
            { "pickaxe_id_079_modernmilitary", "Caliper" },
            { "pickaxe_id_080_scuba", "Harpoon Axe" },
            { "pickaxe_id_081_streetracercobra", "Clutch Axe" },
            { "pickaxe_id_082_sushichef", "Filet Axe" },
            { "pickaxe_id_083_exercise", "Axercise" },
            { "pickaxe_id_084_durrburgerhero", "Patty Whacker" },
            { "pickaxe_id_085_wukong", "Jingu Bang" }
        };

        public static Hashtable Gliders = new Hashtable
        {
            {"glider_id_001", "Aerial Assault One"},
            {"glider_id_002_medieval", "Sir Glider the Brave"},
            {"glider_id_003_district", "Royale X"},
            {"glider_id_004_disco", "Get Down!"},
            {"glider_id_005_holidaysweater", "Cozy Coaster"},
            {"glider_id_006_wintercamo", "Snow Squall"},
            {"glider_id_007_turtleshell", "Half Shell"},
            {"glider_id_008_graffiti", "Zephyr"},
            {"glider_id_009_candycoat", "Gum Drop"},
            {"glider_id_010_storm", "Cloud Strike"},
            {"glider_id_011_jollyroger", "Jolly Roger"},
            {"glider_id_012_teddybear", "Bear Force One"},
            {"glider_id_013_psblue", "Blue Streak"},
            {"glider_id_014_dragon", "Royale Dragon"},
            {"glider_id_015_brite", "Rainbow Rider"},
            {"glider_id_016_tactical", "Carbon"},
            {"glider_id_017_assassin", "High Octane"},
            {"glider_id_018_twitch", "Slipstream"},
            {"glider_id_020_fighter", "Fighter Kite"},
            {"glider_mig", "Raptor"},
            {"glider_military", "Warthog"},
            {"glider_prismatic", "Prismatic"},
            {"glider_roadtrip", "Roadtrip"},
            {"glider_stealth", "Stealth"},
            {"glider_venom", "Wasp"},
            {"glider_voyager", "Voyager"},
            {"glider_warthog", "Mako"},
            {"glider_id_019_taxi", "Checker"},
            {"glider_id_021_scavenger", "Rusty Rider"},
            {"glider_id_022_rockerpunk", "Stage Dive"},
            {"glider_id_023_cuchulainn", "Storm Sigil"},
            {"glider_id_024_reaper", "Feathered Flyer"},
            {"glider_id_025_shuttlea", "Orbital Shuttle"},
            {"glider_id_026_shuttleb", "Deep Space Lander"},
            {"glider_id_027_satelite", "Planetary Probe"},
            {"glider_id_028_googly", "Googly"},
            {"glider_id_029_pajamaparty", "Fossil Flyer"},
            {"glider_id_030_circuitbreaker", "Mainframe"}
        };

        public static Hashtable Backblings = new Hashtable
        {
            {"001_bluesquire", "Squire Shield"},
            {"002_royaleknight", "Royale Shield"},
            {"003_redknight", "Red Shield"},
            {"004_blackknight", "Black Shield"},
            {"005_raptor", "Raptor Satchel"},
            {"SkiDude", "Alpine Accessories"},
            {"SkiGirl", "Mogul Ski Bag"},
            {"022_cupid", "Love Wings"},
            {"023_pinkbear", "Cuddle Bow"},
            {"024_space", "Astro"},
            {"025_tactical", "Precision"},
            {"026_brite", "Brite Bag"},
            {"027_scavenger", "Rust Bucket"},
            {"028_spaceblack", "Dark Matter"},
            {"029_retrogrey", "Backup Plan"},
            {"030_tacticalrogue", "Catalyst"},
            {"031_dinosaur", "Scaly"},
            {"032_foundermale", "Pursuit"},
            {"033_founderfemale", "Skirmish"},
            {"034_rockerpunk", "Six String"},
            {"035_scathach", "Buckler"},
            {"036_raven", "Iron Cage"},
            {"037_bunnymale", "Hard Boiled"},
            {"038_bunnyfemale", "Eggshell"},
            {"039_spaceblackfemale", "Dark Void"},
            {"040_wukong", "Royale Flags"},
            {"041_pajamaparty", "Hatchling"},
            {"042_fishhead", "Fish Tank"},
            {"043_pizza", "Special Delivery"},
            {"044_robo", "Steelcast"}
        };

        public static Hashtable Outfits = new Hashtable
        {
            {"009_athena_commando_m", "Tracker"},
            {"010_athena_commando_m", "Ranger"},
            {"011_athena_commando_m", "Scout"},
            {"012_athena_commando_m", "Trooper"},
            {"013_athena_commando_f", "Renegade"},
            {"014_athena_commando_f", "Pathfinder"},
            {"015_athena_commando_f", "Assault Trooper"},
            {"016_athena_commando_f", "Commando"},
            {"017_athena_commando_m", "Aerial Assault Trooper"},
            {"018_athena_commando_m", "Recon Scout"},
            {"019_athena_commando_m", "Infiltrator"},
            {"020_athena_commando_m", "Special Forces"},
            {"021_athena_commando_f", "Brawler"},
            {"022_athena_commando_f", "Recon Expert"},
            {"023_athena_commando_f", "Munitions Expert"},
            {"024_athena_commando_f", "Recon Specialist"},
            {"025_athena_commando_m", "First strike Specialist"},
            {"026_athena_commando_m", "Desperado"},
            {"027_athena_commando_f", "Survival Specialist"},
            {"028_athena_commando_f", "Renegade Raider"},
            {"029_athena_commando_f_halloween", "Ghoul Trooper"},
            {"030_athena_commando_m_halloween", "Skull Trooper"},
            {"031_athena_commando_m_retro", "Raptor"},
            {"032_athena_commando_m_medieval", "Blue Squire"},
            {"033_athena_commando_f_medieval", "Royale Knight"},
            {"034_athena_commando_f_medieval", "Red Knight"},
            {"035_athena_commando_m_medieval", "Black Knight"},
            {"036_athena_commando_m_wintercamo", "Absolute Zero"},
            {"037_athena_commando_f_wintercamo", "Arctic Assassin"},
            {"038_athena_commando_m_disco", "Funk Ops"},
            {"039_athena_commando_f_disco", "Sparkle Specialist"},
            {"040_athena_commando_m_district", "Devastator"},
            {"041_athena_commando_f_district", "Dominator"},
            {"042_athena_commando_m_cyberpunk", "Circuit Breaker"},
            {"043_athena_commando_f_stealth", "Shadow Ops"},
            {"044_athena_commando_f_scipop", "Brite Bomber"},
            {"045_athena_commando_m_holidaysweater", "Yuletide Ranger"},
            {"046_athena_commando_f_holidaysweater", "Nog Ops"},
            {"047_athena_commando_f_holidayreindeer", "Red-Nosed Raider"},
            {"048_athena_commando_f_holidaygingerbread", "Ginger Gunner"},
            {"049_athena_commando_m_holidaygingerbread", "Merry Marauder"},
            {"050_athena_commando_m_holidaynutcracker", "Crackshot"},
            {"051_athena_commando_m_holidayelf", "Codename E.L.F."},
            {"052_athena_commando_f_psblue", "Blue Team Leader"},
            {"athena_commando_m_skidude", "Alpine Ace"}, // NOTE: Each country has its own version, but too lazy to add all of them.
            {"athena_commando_f_skigirl", "Mogul Master"}, // NOTE: Same for the female version
            {"069_athena_commando_f_pinkbear", "Pink Bear"},
            {"070_athena_commando_m_cupid", "Love Ranger"},
            {"071_athena_commando_m_wukong", "Wukong"},
            {"072_athena_commando_m_scout", "Sash Sergeant"},
            {"073_athena_commando_f_scuba", "Snorkel Ops"},
            {"074_athena_commando_f_stripe", "Jungle Scout"},
            {"075_athena_commando_f_stripe", "Tactics Officer"},
            {"076_athena_commando_f_sup", "Dazzle"},
            {"077_athena_commando_m_sup", "Hyperion"},
            {"078_athena_commando_m_camo", "Highrise Assault Trooper"},
            {"079_athena_commando_f_camo", "Tower Recon Specialist"},
            {"080_athena_commando_m_space", "Mission Specialist"},
            {"081_athena_commando_f_space", "Moonwalker"},
            {"082_athena_commando_m_scavenger", "Rust Lord"},
            {"083_athena_commando_f_tactical", "Elite Agent"},
            {"084_athena_commando_m_assassin", "The Reaper"},
            {"085_athena_commando_m_twitch", "Sub Commander"},
            {"086_athena_commando_m_redsilk", "Crimson Scout"},
            {"087_athena_commando_f_redsilk", "Scarlet Defender"},
            {"088_athena_commando_m_spaceblack", "Dark Voyager"},
            {"089_athena_commando_m_retrogrey", "Havoc"},
            {"090_athena_commando_m_tactical", "Rogue Agent"},
            {"091_athena_commando_m_redshirt", "Radiant Striker"},
            {"092_athena_commando_f_redshirt", "Brilliant Striker"},
            {"093_athena_commando_m_dinosaur", "Rex"},
            {"094_athena_commando_m_rider", "Burnout"},
            {"095_athena_commando_m_founder", "Warpaint"},
            {"096_athena_commando_f_founder", "Rose Team Leader"},
            {"097_athena_commando_f_rockerpunk", "Power Chord"},
            {"098_athena_commando_f_stpatty", "Sgt. Green Clover"},
            {"099_athena_commando_f_scathach", "Highland Warrior"},
            {"100_athena_commando_m_cuchulainn", "Battle Hound"},
            {"101_athena_commando_m_stealth", "Midnight Ops"},
            {"102_athena_commando_m_raven", "Raven"},
            {"103_athena_commando_m_bunny", "Rabbit Raider"},
            {"104_athena_commando_f_bunny", "Bunny Brawler"},
            {"105_athena_commando_f_spaceblackfemale", "Dark Vanguard"},
            {"106_athena_commando_f_taxi", "Whiplash"},
            {"107_athena_commando_f_pajamaparty", "Tricera Ops"},
            {"108_athena_commando_m_fishhead", "Leviathan"},
            {"109_athena_commando_m_pizza", "Tomatohead"},
            {"110_athena_commando_f_circuitbreaker", "Cipher"},
            {"111_athena_commando_f_robo", "Steelsight"},
            {"112_Athena_Commando_M_Brite", "Brite Gunner"}
        };
    }
}